@BookStoreAPI_HostAddress = http://localhost:5088

GET {{BookStoreAPI_HostAddress}}/Books/
Accept: application/json

###
GET {{BookStoreAPI_HostAddress}}/Books?Title=[tittel]
Accept: application/json

###
GET {{BookStoreAPI_HostAddress}}/Books?PublicationYear=2022
Accept: application/json

###
GET {{BookStoreAPI_HostAddress}}/Books?Author=Ola
Accept: application/json

###
POST {{BookStoreAPI_HostAddress}}/Books/
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "title": "Fishing Guide",
  "author": "Joe Ma",
  "publicationYear": 2050,
  "isbn": "9788057066422",
  "inStock": 100
}

###
PUT {{BookStoreAPI_HostAddress}}/Books/
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "title": "Fishing Guide",
  "author": "Joe Ma",
  "publicationYear": 2050,
  "isbn": "9788057066422",
  "inStock": 100
}

###
DELETE {{BookStoreAPI_HostAddress}}/Books/